name: "Setup darklua"
description: "Set up your GitHub Actions workflow with a specific version of darklua"
branding:
  icon: "package"
  color: "purple"

inputs:
  version:
    description: "What version to use for darklua?"
    required: false
    default: "latest"
  cache:
    description: "Whether to cache the downloaded darklua binary between runs"
    required: false
    default: "true"
outputs:
  version:
    description: "The exact darklua version that was installed"
runs:
  using: node24
  main: dist/index.mjs
